version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-stretch-node
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PG_DATABASE: postgres
          PG_PASSWORD: pass
          PG_USER: postgres
          SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      - image: circleci/postgres:9.6-postgis-ram
        environment:
          POSTGRES_PASSWORD: pass
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      # - ruby/bundle-install
      # - run:
      #   name: Wait for DB
      #   command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # - run:
      #   name: Database setup
      #   command: bundle exec rake db:schema:load --trace

