version: '3'
services:
  app:
    image: 813281301262.dkr.ecr.us-east-2.amazonaws.com/osakaya-tm
    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid;bundle exec rails s -b 0.0.0.0"
    ports:
      - '80:3000'
    working_dir: /var/src/app
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
